name: Release SmartDNS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'new release tag(e.g. 38)'
        required: true

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-build:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - toolchain: aarch64-linux-musl
            openssl: linux-aarch64
            pkgarch: aarch64
          - toolchain: arm-linux-musleabi
            openssl: linux-armv4
            pkgarch: arm
          - toolchain: mips-linux-musl
            openssl: linux-mips32
            pkgarch: mips
          - toolchain: mipsel-linux-musl
            openssl: linux-mips32
            pkgarch: mipsel
          - toolchain: i686-linux-musl
            openssl: linux-x86
            pkgarch: x86
          - toolchain: x86_64-linux-musl
            openssl: linux-x86_64
            pkgarch: x86_64

    runs-on: ubuntu-latest
    container: muslcc/x86_64:${{ matrix.toolchain }}

    steps:
      - name: Install build tools
        run: apk add --no-cache git make tar curl perl

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build openssl
        run: |
          export OPENSSL_VER=3.0.12
          export OPENSSL_OPTIONS="${{ matrix.openssl }} no-tests no-ssl3 no-weak-ssl-ciphers no-shared no-idea -DOPENSSL_NO_SECURE_MEMORY"
          mkdir -p /build/openssl
          cd /build/openssl
          curl -sSL https://www.openssl.org/source/openssl-${OPENSSL_VER}.tar.gz | tar --strip-components=1 -zxv
          ./config --prefix=/opt/build $OPENSSL_OPTIONS
          make all -j8
          make install_sw

      - name: Build
        run: |
          cc -v
          export EXTRA_CFLAGS="-I /opt/build/include -DFEATURE_CHECK_EDNS=1"
          export LDFLAGS="-L /opt/build/lib -L /opt/build/lib64"
          ./package/build-pkg.sh --platform linux --arch ${{ matrix.pkgarch }}  --static

      - name: Set up directories
        run: |
          mkdir .artifacts
          mkdir .package

      - name: Create binary atrifacts
        run: |
          cp package/smartdns.*.tar.gz .artifacts/
          cp src/smartdns .artifacts/smartdns-${{ matrix.pkgarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: btop-${{ matrix.toolchain }}
          path: '.artifacts/**'
