name: SmartDNS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-build:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - toolchain: aarch64-linux-musl
            openssl: linux-aarch64
            pkgarch: aarch64
          - toolchain: arm-linux-musleabi
            openssl: linux-armv4
            pkgarch: arm
          - toolchain: mips-linux-musl
            openssl: linux-mips32
            pkgarch: mips
          - toolchain: mipsel-linux-musl
            openssl: linux-mips32
            pkgarch: mipsel
          - toolchain: i686-linux-musl
            openssl: linux-x86
            pkgarch: x86
          - toolchain: x86_64-linux-musl
            openssl: linux-x86_64
            pkgarch: x86_64

    runs-on: ubuntu-latest
    container: muslcc/x86_64:${{ matrix.toolchain }}

    steps:
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ matrix.toolchain }}
          restore-keys: ${{ matrix.toolchain }}
          
      - name: Install build tools
        run: apk add --no-cache git make tar curl perl coreutils dpkg ccache

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build openssl
        run: |
          export OPENSSL_VER=3.0.12
          export OPENSSL_OPTIONS="${{ matrix.openssl }} no-tests no-ssl3 no-weak-ssl-ciphers no-shared no-idea -DOPENSSL_NO_SECURE_MEMORY"
          export CC="ccache cc"
          mkdir -p /build/openssl
          cd /build/openssl
          curl -sSL https://www.openssl.org/source/openssl-${OPENSSL_VER}.tar.gz | tar --strip-components=1 -zxv
          ./config --prefix=/opt/build $OPENSSL_OPTIONS
          make all -j8
          make install_sw

      - name: Build
        run: |
          export EXTRA_CFLAGS="-I /opt/build/include -DFEATURE_CHECK_EDNS=1"
          export CC="ccache cc"
          export LDFLAGS="-L /opt/build/lib -L /opt/build/lib64 -Wl,--whole-archive -latomic -Wl,--no-whole-archive"
          ./package/build-pkg.sh --platform linux --arch ${{ matrix.pkgarch }}  --static
          ./package/build-pkg.sh --platform optware --arch ${{ matrix.pkgarch }}  --only-package
          ./package/build-pkg.sh --platform openwrt --arch ${{ matrix.pkgarch }}  --only-package
          ./package/build-pkg.sh --platform debian --arch ${{ matrix.pkgarch }}  --only-package
          ./package/build-pkg.sh --platform luci --arch all --only-package
          ./package/build-pkg.sh --platform luci-compat --arch all --only-package

      - name: Set up directories
        run: |
          mkdir .artifacts
          mkdir .package

      - name: Create binary atrifacts
        run: |
          cp package/smartdns.* .artifacts/ -avf
          cp package/luci-app-smartdns.* .artifacts/
          cp src/smartdns .artifacts/smartdns-${{ matrix.pkgarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: smartdns-${{ matrix.pkgarch }}
          path: '.artifacts/**'
