name: Release SmartDNS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'new release tag(e.g. 38)'
        required: true

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-build:
    continue-on-error: true
    strategy:
      matrix:
        toolchain:
          - aarch64-linux-musl
          - arm-linux-musleabi
          - i686-linux-musl
          - mips-linux-musl
          - mipsel-linux-musl
          - x86_64-linux-musl

    runs-on: ubuntu-latest
    container: muslcc/x86_64:${{ matrix.toolchain }}

    steps:
      - name: Install build tools
        run: apk add --no-cache git make tar openssl-dev

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          cc -v
          make STATIC=true

      - name: Make executable
        run: chmod +x bin/*

      - name: Set up directories
        run: |
          mkdir .artifacts
          mkdir .package

      - name: Create binary atrifacts
        run: |
          TOOLCHAIN=${{ matrix.toolchain }}
          GIT_HASH=$(git rev-parse --short "${{ github.sha }}")
          FILENAME=btop-${TOOLCHAIN/linux-musl/}-$GIT_HASH
          cp bin/btop .artifacts/$FILENAME

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: btop-${{ matrix.toolchain }}
          path: '.artifacts/**'
